# src/underwater_tracking/domain/__init__.py
"""Domain contracts for the underwater tracking assistant.

UI frame contracts (``ui_models``) are re-exported explicitly; truth
carriers stay confined to ``ui_models`` and the evaluation-only path.
"""

from underwater_tracking.domain.ui_models import (
    AdversaryView,
    BearingRayView,
    BrainView,
    CarrierView,
    CommunicationLinkView,
    CovarianceEllipse,
    EstimateQualityView,
    EvaluationFrame,
    EventView,
    GroupQualityView,
    GroupView,
    IntentView,
    IntelligenceView,
    LedgerView,
    MapBounds,
    MetricView,
    OperationalFrame,
    OperationalSchemeView,
    PlanTimelineView,
    PlanView,
    Point2D,
    PredictionCorridorView,
    TargetEstimateView,
    TimelineFactorView,
    TimelinePlanView,
    UUVView,
    USVView,
)
from underwater_tracking.domain.models import CarrierState, CarrierStatus, DeploymentState

__all__ = [
    "AdversaryView",
    "BearingRayView",
    "BrainView",
    "CarrierState",
    "CarrierStatus",
    "CarrierView",
    "CommunicationLinkView",
    "CovarianceEllipse",
    "DeploymentState",
    "EstimateQualityView",
    "EvaluationFrame",
    "EventView",
    "GroupQualityView",
    "GroupView",
    "IntentView",
    "IntelligenceView",
    "LedgerView",
    "MapBounds",
    "MetricView",
    "OperationalFrame",
    "OperationalSchemeView",
    "PlanTimelineView",
    "PlanView",
    "Point2D",
    "PredictionCorridorView",
    "TargetEstimateView",
    "TimelineFactorView",
    "TimelinePlanView",
    "UUVView",
    "USVView",
]
