# src/underwater_tracking/domain/__init__.py
"""Domain contracts for the underwater tracking assistant.

UI frame contracts (``ui_models``) are re-exported explicitly; truth
carriers stay confined to ``ui_models`` and the evaluation-only path.
"""

from underwater_tracking.domain.ui_models import (
    AdversaryView,
    BearingRayView,
    BrainView,
    CarrierView,
    CommunicationLinkView,
    CovarianceEllipse,
    EstimateQualityView,
    EvaluationFrame,
    EventView,
    GroupQualityView,
    GroupView,
    IntentView,
    IntelligenceView,
    LedgerView,
    MapBounds,
    MetricView,
    OperationalFrame,
    OperationalSchemeView,
    PlanTimelineView,
    PlanView,
    Point2D,
    PredictionCorridorView,
    RegionalPlanView,
    RegionTaskView,
    TargetEstimateView,
    TimelineFactorView,
    TimelinePlanView,
    TrackingEffectView,
    UUVView,
    USVView,
)
from underwater_tracking.domain.models import CarrierState, CarrierStatus, DeploymentState
from underwater_tracking.domain.regional_models import (
    CommunicationRequirement,
    GridSpec,
    RegionCell,
    RegionTask,
    RegionalMissionCandidate,
    RegionalPolicy,
    RegionalStrategySet,
    SonarPolicy,
    TargetRegionPlan,
    TimeWindow,
    UUVRegionalPolicy,
    UUVRegionalStrategySet,
)

__all__ = [
    "AdversaryView",
    "BearingRayView",
    "BrainView",
    "CarrierState",
    "CarrierStatus",
    "CarrierView",
    "CommunicationLinkView",
    "CovarianceEllipse",
    "DeploymentState",
    "EstimateQualityView",
    "EvaluationFrame",
    "EventView",
    "GroupQualityView",
    "GroupView",
    "IntentView",
    "IntelligenceView",
    "LedgerView",
    "MapBounds",
    "MetricView",
    "OperationalFrame",
    "OperationalSchemeView",
    "PlanTimelineView",
    "PlanView",
    "Point2D",
    "PredictionCorridorView",
    "RegionalPlanView",
    "RegionTaskView",
    "TargetEstimateView",
    "TimelineFactorView",
    "TimelinePlanView",
    "TrackingEffectView",
    "UUVView",
    "USVView",
    "CommunicationRequirement",
    "GridSpec",
    "RegionCell",
    "RegionTask",
    "RegionalMissionCandidate",
    "RegionalPolicy",
    "RegionalStrategySet",
    "SonarPolicy",
    "TargetRegionPlan",
    "TimeWindow",
    "UUVRegionalPolicy",
    "UUVRegionalStrategySet",
]
